#pragma once

#include <stdint.h>

/* XXX: Comment out this line for a non-test network */
//#define DFD_TEST_NETWORK

#define DFD_TEST_NETWORK_VERSION                            83 // autogenerated

#define DFD_BLOCKCHAIN_DATABASE_VERSION                     uint64_t( 201 )

/**
 *  The address prepended to string representation of
 *  addresses.
 *
 *  Changing these parameters will result in a hard fork.
 */
#define DFD_ADDRESS_PREFIX                                  "D"
#define DFD_BLOCKCHAIN_SYMBOL                               "DFD"
#define DFD_BLOCKCHAIN_NAME                                 "DFD"
#define DFD_BLOCKCHAIN_DESCRIPTION                          "Decentralized Financial Data System"
			
#define DFD_BLOCKCHAIN_PRECISION                            (int64_t(100000))

#define DFD_BLOCKCHAIN_MAX_UIA_MARKET_FEE                   10000
#define DFD_BLOCKCHAIN_BLOCK_INTERVAL_SEC                   int64_t(10)
#define DFD_BLOCKCHAIN_BLOCKS_PER_HOUR                      ((60*60)/DFD_BLOCKCHAIN_BLOCK_INTERVAL_SEC)
#define DFD_BLOCKCHAIN_BLOCKS_PER_DAY                       (DFD_BLOCKCHAIN_BLOCKS_PER_HOUR*int64_t(24))
#define DFD_BLOCKCHAIN_BLOCKS_PER_YEAR                      (DFD_BLOCKCHAIN_BLOCKS_PER_DAY*int64_t(365))

#define DFD_BLOCKCHAIN_NUM_DELEGATES                        uint32_t(9)
#define DFD_MAX_DELEGATE_PAY_PER_BLOCK                      int64_t( 10 * DFD_BLOCKCHAIN_PRECISION ) 
#define DFD_BLOCKCHAIN_MAX_UNDO_HISTORY                     DFD_BLOCKCHAIN_BLOCKS_PER_HOUR

#define DFD_BLOCKCHAIN_REGISTER_ACCOUNT_FEE                 int64_t( 10 * DFD_BLOCKCHAIN_PRECISION ) 

#define DFD_BLOCKCHAIN_MAX_SLATE_SIZE                       (DFD_BLOCKCHAIN_NUM_DELEGATES + (DFD_BLOCKCHAIN_NUM_DELEGATES/10))
#define DFD_BLOCKCHAIN_MAX_MESSAGE_SIZE                     2048
#define DFD_BLOCKCHAIN_MAX_FREE_MESSAGE_SIZE                1024
#define DFD_BLOCKCHAIN_MAX_SOFT_MAX_MESSAGE_SIZE            40
#define DFD_BLOCKCHAIN_MIN_MESSAGE_FEE_COE                  100
#define DFD_BLOCKCHAIN_MAX_TRANSACTION_EXPIRATION_SEC       (60*60*24*2)
#define DFD_BLOCKCHAIN_MAX_MEMO_SIZE                        19 // bytes
#define DFD_BLOCKCHAIN_EXTENDED_MEMO_SIZE                   32 // bytes
#define DFD_BLOCKCHAIN_MAX_EXTENDED_MEMO_SIZE               (DFD_BLOCKCHAIN_MAX_MEMO_SIZE + DFD_BLOCKCHAIN_EXTENDED_MEMO_SIZE)

#define DFD_DEFAULT_TRANSACTION_FEE                         (int64_t(1000)) // 
#define DFD_DEFAULT_TRANSACTION_EXPIRATION_SEC              (60*60)
#define DFD_DEFAULT_CONTRACT_MARGIN                         (int64_t)( 10 * DFD_BLOCKCHAIN_PRECISION )


#define DFD_BLOCKCHAIN_ASSET_SHADOW							int64_t( 72897000 * DFD_BLOCKCHAIN_PRECISION ) 



/**
 *  The maximum amount that can be issued for user assets.
 *
 *  10^18 / 2^63 < 1  however, to support representing all share values as a double in
 *  languages like java script, we must stay within the epsilon so
 *
 *  10^15 / 2^53 < 1 allows all values to be represented as a double or an int64
 */
#define DFD_BLOCKCHAIN_MAX_SHARES                           (int64_t(2100)*int64_t(1000)*int64_t(1000)*int64_t(1000)*int64_t(1000))

#define DFD_BLOCKCHAIN_MIN_NAME_SIZE                        1
#define DFD_BLOCKCHAIN_MAX_NAME_SIZE                        63
#define DFD_BLOCKCHAIN_MAX_NAME_DATA_SIZE                   (1024*64)

#define DFD_BLOCKCHAIN_MAX_SDFD_SYMBOL_SIZE                  8 // characters
#define DFD_BLOCKCHAIN_MIN_SYMBOL_SIZE                      3 // characters
#define DFD_BLOCKCHAIN_MAX_SYMBOL_SIZE                      12 // characters

#define DFD_BLOCKCHAIN_MIN_BURN_FEE                         DFD_BLOCKCHAIN_PRECISION * 1 // 1 

#ifdef DFD_TEST_NETWORK
#define DFD_BLOCKCHAIN_VOTE_UPDATE_PERIOD_SEC               10
#else
#define DFD_BLOCKCHAIN_VOTE_UPDATE_PERIOD_SEC               (60*60) // 1 hour
#endif

#define DFD_BLOCKCHAIN_MIN_FEEDS                            ((DFD_BLOCKCHAIN_NUM_DELEGATES/2) + 1)
#define DFD_BLOCKCHAIN_MINIMUM_SHORT_ORDER_SIZE             (DFD_BLOCKCHAIN_PRECISION*100)
#define DFD_BLOCKCHAIN_MIN_YIELD_PERIOD_SEC                 (60*60*24) // 24 hours
#define DFD_BLOCKCHAIN_MAX_YIELD_PERIOD_SEC                 (DFD_BLOCKCHAIN_BLOCKS_PER_YEAR * DFD_BLOCKCHAIN_BLOCK_INTERVAL_SEC) // 1 year

#ifdef DFD_TEST_NETWORK
#define DFD_BLOCKCHAIN_MAX_SHORT_PERIOD_SEC                 (2*60*60) // 2 hours
#else
#define DFD_BLOCKCHAIN_MAX_SHORT_PERIOD_SEC                 (30*24*60*60) // 1 month
#endif
#define DFD_BLOCKCHAIN_MAX_SHORT_APR_PCT                    (uint64_t(50))

#define DFD_BLOCKCHAIN_MCALL_D2C_NUMERATOR                  1
#define DFD_BLOCKCHAIN_MCALL_D2C_DENOMINATOR                2

// TODO: This stuff only matters for propagation throttling; should go somewhere else
#define DFD_BLOCKCHAIN_DEFAULT_RELAY_FEE                    1 // 
#define DFD_BLOCKCHAIN_MAX_TRX_PER_SECOND                   1000  // (1000)
#define DFD_BLOCKCHAIN_MAX_PENDING_QUEUE_SIZE               10000 // (DFD_BLOCKCHAIN_MAX_TRX_PER_SECOND * DFD_BLOCKCHAIN_BLOCK_INTERVAL_SEC)

#define DFD_BLOCKCHAIN_REVALIDATE_MAX_TRX_COUNT             (DFD_BLOCKCHAIN_MAX_TRX_PER_SECOND * DFD_BLOCKCHAIN_BLOCK_INTERVAL_SEC)


// for contract
#define  CONTRACT_ADDRESS_PREFIX "c" 
#define  SCRIPT_ID_PREFIX "s" 
#define  MULTI_ADDRESS_PREFIX "M"


#define  CONTRACT_MAX_BYTECODE_SIZE   (1 * 1024 * 1024)  //just set to the limit of block size
#define  CONTRACT_MAX_NAME_SIZE  32 
#define  CONTRACT_MAX_DESCRIPTION_SIZE  256
#define  LIMIT_PRICE 1
#define  LIMIT_PER_AMOUNT 1000
#define  CONTRACT_PARAM_MAX_LEN  1024

#define  CONTRACT_OFFLINE_LIMIT_MAX     (1024*1024*1024) 
#define  CONTRACT_TESTING_LIMIT_MAX     (1024*1024*1024) 

// for event
#define  EVENT_PARAM_MAX_LEN  1024
#define  EVENT_TYPE_MAX_LEN   256

#define DFD_BLOCKCHAIN_FREESIGNATURE_LIMIT	10
#define DFD_BLOCKCHAIN_MAX_SIGNAGTURE_NUM   1000
#define DFD_BLOCKCHAIN_EXTRA_SIGNATURE_FEE  1000
#define DFD_BLOCKCHAIN_TRANSACTION_MAX_DEPOSIT_NUM 100


// reward fork
#ifdef DFD_TEST_NETWORK
#define HARD_FORK_REWARD_HEIGHT 10
#define REWARD_HALF_BLOCK_COUNT 20
#else
#define HARD_FORK_REWARD_HEIGHT 180000
#define REWARD_HALF_BLOCK_COUNT 777600
#endif

